# Form implementation generated from reading ui file '.\ParamDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(125, 120)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBox_max = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_max.setMaximum(6553600.0)
        self.doubleSpinBox_max.setObjectName("doubleSpinBox_max")
        self.gridLayout.addWidget(self.doubleSpinBox_max, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBox_min = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_min.setObjectName("doubleSpinBox_min")
        self.gridLayout.addWidget(self.doubleSpinBox_min, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.doubleSpinBox_gain = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_gain.setDecimals(2)
        self.doubleSpinBox_gain.setMinimum(0.01)
        self.doubleSpinBox_gain.setMaximum(100.0)
        self.doubleSpinBox_gain.setSingleStep(0.01)
        self.doubleSpinBox_gain.setProperty("value", 1.0)
        self.doubleSpinBox_gain.setObjectName("doubleSpinBox_gain")
        self.gridLayout.addWidget(self.doubleSpinBox_gain, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "参数设置"))
        self.label_4.setText(_translate("Dialog", "参数名称"))
        self.label.setText(_translate("Dialog", "最大数值"))
        self.label_2.setText(_translate("Dialog", "最小数值"))
        self.label_3.setText(_translate("Dialog", "数值增益"))
