# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWin(object):

    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(1167, 776)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWin.sizePolicy().hasHeightForWidth())
        MainWin.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.device_select = QtWidgets.QWidget()
        self.device_select.setObjectName("device_select")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.device_select)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.device_select)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.verticalLayout.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.verticalLayout.addWidget(self.label_28)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_serialCheck = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_serialCheck.sizePolicy().hasHeightForWidth())
        self.pushButton_serialCheck.setSizePolicy(sizePolicy)
        self.pushButton_serialCheck.setObjectName("pushButton_serialCheck")
        self.verticalLayout_2.addWidget(self.pushButton_serialCheck)
        self.comboBox_portName = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_portName.sizePolicy().hasHeightForWidth())
        self.comboBox_portName.setSizePolicy(sizePolicy)
        self.comboBox_portName.setObjectName("comboBox_portName")
        self.verticalLayout_2.addWidget(self.comboBox_portName)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_baudrate.sizePolicy().hasHeightForWidth())
        self.comboBox_baudrate.setSizePolicy(sizePolicy)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_baudrate)
        self.comboBox_dataBit = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_dataBit.sizePolicy().hasHeightForWidth())
        self.comboBox_dataBit.setSizePolicy(sizePolicy)
        self.comboBox_dataBit.setObjectName("comboBox_dataBit")
        self.comboBox_dataBit.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_dataBit)
        self.comboBox_stopBit = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_stopBit.sizePolicy().hasHeightForWidth())
        self.comboBox_stopBit.setSizePolicy(sizePolicy)
        self.comboBox_stopBit.setObjectName("comboBox_stopBit")
        self.comboBox_stopBit.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_stopBit)
        self.comboBox_parity = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_parity.sizePolicy().hasHeightForWidth())
        self.comboBox_parity.setSizePolicy(sizePolicy)
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_parity)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_serialOpen = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_serialOpen.sizePolicy().hasHeightForWidth())
        self.pushButton_serialOpen.setSizePolicy(sizePolicy)
        self.pushButton_serialOpen.setObjectName("pushButton_serialOpen")
        self.horizontalLayout_4.addWidget(self.pushButton_serialOpen)
        self.pushButton_serialClose = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_serialClose.sizePolicy().hasHeightForWidth())
        self.pushButton_serialClose.setSizePolicy(sizePolicy)
        self.pushButton_serialClose.setObjectName("pushButton_serialClose")
        self.horizontalLayout_4.addWidget(self.pushButton_serialClose)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.device_select)
        self.groupBox_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_5.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_5.addWidget(self.label_35)
        self.label_32 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_5.addWidget(self.label_32)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboBox_i2c_addrMode = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_i2c_addrMode.sizePolicy().hasHeightForWidth())
        self.comboBox_i2c_addrMode.setSizePolicy(sizePolicy)
        self.comboBox_i2c_addrMode.setObjectName("comboBox_i2c_addrMode")
        self.comboBox_i2c_addrMode.addItem("")
        self.comboBox_i2c_addrMode.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_i2c_addrMode)
        self.comboBox_i2c_speed = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_i2c_speed.sizePolicy().hasHeightForWidth())
        self.comboBox_i2c_speed.setSizePolicy(sizePolicy)
        self.comboBox_i2c_speed.setObjectName("comboBox_i2c_speed")
        self.comboBox_i2c_speed.addItem("")
        self.comboBox_i2c_speed.addItem("")
        self.comboBox_i2c_speed.addItem("")
        self.comboBox_i2c_speed.addItem("")
        self.comboBox_i2c_speed.addItem("")
        self.comboBox_i2c_speed.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_i2c_speed)
        self.comboBox_i2c_mode = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_i2c_mode.sizePolicy().hasHeightForWidth())
        self.comboBox_i2c_mode.setSizePolicy(sizePolicy)
        self.comboBox_i2c_mode.setObjectName("comboBox_i2c_mode")
        self.comboBox_i2c_mode.addItem("")
        self.comboBox_i2c_mode.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_i2c_mode)
        self.lineEdit_i2c_addr = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_i2c_addr.setObjectName("lineEdit_i2c_addr")
        self.verticalLayout_7.addWidget(self.lineEdit_i2c_addr)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_i2cOpen = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_i2cOpen.sizePolicy().hasHeightForWidth())
        self.pushButton_i2cOpen.setSizePolicy(sizePolicy)
        self.pushButton_i2cOpen.setObjectName("pushButton_i2cOpen")
        self.horizontalLayout_3.addWidget(self.pushButton_i2cOpen)
        self.pushButton_i2cClose = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_i2cClose.sizePolicy().hasHeightForWidth())
        self.pushButton_i2cClose.setSizePolicy(sizePolicy)
        self.pushButton_i2cClose.setObjectName("pushButton_i2cClose")
        self.horizontalLayout_3.addWidget(self.pushButton_i2cClose)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.device_select)
        self.groupBox_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_37 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.label_36 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_9.addWidget(self.label_36)
        self.label_38 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_9.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_spi_mode = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_spi_mode.sizePolicy().hasHeightForWidth())
        self.comboBox_spi_mode.setSizePolicy(sizePolicy)
        self.comboBox_spi_mode.setObjectName("comboBox_spi_mode")
        self.comboBox_spi_mode.addItem("")
        self.comboBox_spi_mode.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_spi_mode)
        self.comboBox_spi_format = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_spi_format.sizePolicy().hasHeightForWidth())
        self.comboBox_spi_format.setSizePolicy(sizePolicy)
        self.comboBox_spi_format.setObjectName("comboBox_spi_format")
        self.comboBox_spi_format.addItem("")
        self.comboBox_spi_format.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_spi_format)
        self.comboBox_spi_speed = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_spi_speed.sizePolicy().hasHeightForWidth())
        self.comboBox_spi_speed.setSizePolicy(sizePolicy)
        self.comboBox_spi_speed.setObjectName("comboBox_spi_speed")
        self.comboBox_spi_speed.addItem("")
        self.comboBox_spi_speed.addItem("")
        self.comboBox_spi_speed.addItem("")
        self.comboBox_spi_speed.addItem("")
        self.comboBox_spi_speed.addItem("")
        self.comboBox_spi_speed.addItem("")
        self.comboBox_spi_speed.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_spi_speed)
        self.comboBox_spi_workmode = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_spi_workmode.sizePolicy().hasHeightForWidth())
        self.comboBox_spi_workmode.setSizePolicy(sizePolicy)
        self.comboBox_spi_workmode.setObjectName("comboBox_spi_workmode")
        self.comboBox_spi_workmode.addItem("")
        self.comboBox_spi_workmode.addItem("")
        self.comboBox_spi_workmode.addItem("")
        self.comboBox_spi_workmode.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_spi_workmode)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_i2cOpen_2 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_i2cOpen_2.sizePolicy().hasHeightForWidth())
        self.pushButton_i2cOpen_2.setSizePolicy(sizePolicy)
        self.pushButton_i2cOpen_2.setObjectName("pushButton_i2cOpen_2")
        self.horizontalLayout_6.addWidget(self.pushButton_i2cOpen_2)
        self.pushButton_i2cClose_2 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_i2cClose_2.sizePolicy().hasHeightForWidth())
        self.pushButton_i2cClose_2.setSizePolicy(sizePolicy)
        self.pushButton_i2cClose_2.setObjectName("pushButton_i2cClose_2")
        self.horizontalLayout_6.addWidget(self.pushButton_i2cClose_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addWidget(self.groupBox_7, 0, 2, 1, 1)
        self.tabWidget.addTab(self.device_select, "")
        self.raw_data = QtWidgets.QWidget()
        self.raw_data.setObjectName("raw_data")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.raw_data)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser_recv = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser_recv.setGeometry(QtCore.QRect(10, 30, 1091, 281))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.textBrowser_recv.sizePolicy().hasHeightForWidth())
        self.textBrowser_recv.setSizePolicy(sizePolicy)
        self.textBrowser_recv.setObjectName("textBrowser_recv")
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_3 = QtWidgets.QGroupBox(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit_Send = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_Send.setGeometry(QtCore.QRect(10, 20, 531, 291))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.textEdit_Send.sizePolicy().hasHeightForWidth())
        self.textEdit_Send.setSizePolicy(sizePolicy)
        self.textEdit_Send.setObjectName("textEdit_Send")
        self.horizontalLayout_12.addWidget(self.groupBox_3)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_12.setSpacing(30)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox_HEXSend = QtWidgets.QCheckBox(self.raw_data)
        self.checkBox_HEXSend.setObjectName("checkBox_HEXSend")
        self.verticalLayout_12.addWidget(self.checkBox_HEXSend)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_sendByTime = QtWidgets.QCheckBox(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_sendByTime.sizePolicy().hasHeightForWidth())
        self.checkBox_sendByTime.setSizePolicy(sizePolicy)
        self.checkBox_sendByTime.setObjectName("checkBox_sendByTime")
        self.horizontalLayout_10.addWidget(self.checkBox_sendByTime)
        self.lineEdit_sendTimer = QtWidgets.QLineEdit(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_sendTimer.sizePolicy().hasHeightForWidth())
        self.lineEdit_sendTimer.setSizePolicy(sizePolicy)
        self.lineEdit_sendTimer.setObjectName("lineEdit_sendTimer")
        self.horizontalLayout_10.addWidget(self.lineEdit_sendTimer)
        self.label_29 = QtWidgets.QLabel(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_10.addWidget(self.label_29)
        self.horizontalLayout_10.setStretch(0, 2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_sendData = QtWidgets.QPushButton(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_sendData.sizePolicy().hasHeightForWidth())
        self.pushButton_sendData.setSizePolicy(sizePolicy)
        self.pushButton_sendData.setObjectName("pushButton_sendData")
        self.horizontalLayout_11.addWidget(self.pushButton_sendData)
        self.pushButton_sendClear = QtWidgets.QPushButton(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_sendClear.sizePolicy().hasHeightForWidth())
        self.pushButton_sendClear.setSizePolicy(sizePolicy)
        self.pushButton_sendClear.setObjectName("pushButton_sendClear")
        self.horizontalLayout_11.addWidget(self.pushButton_sendClear)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.checkBox_HEXRecv = QtWidgets.QCheckBox(self.raw_data)
        self.checkBox_HEXRecv.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_HEXRecv.sizePolicy().hasHeightForWidth())
        self.checkBox_HEXRecv.setSizePolicy(sizePolicy)
        self.checkBox_HEXRecv.setChecked(True)
        self.checkBox_HEXRecv.setTristate(False)
        self.checkBox_HEXRecv.setObjectName("checkBox_HEXRecv")
        self.verticalLayout_12.addWidget(self.checkBox_HEXRecv)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_31 = QtWidgets.QLabel(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_8.addWidget(self.label_31)
        self.textBrowser_sendNum = QtWidgets.QTextBrowser(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.textBrowser_sendNum.sizePolicy().hasHeightForWidth())
        self.textBrowser_sendNum.setSizePolicy(sizePolicy)
        self.textBrowser_sendNum.setObjectName("textBrowser_sendNum")
        self.horizontalLayout_8.addWidget(self.textBrowser_sendNum)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_8)
        self.label_30 = QtWidgets.QLabel(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        self.textBrowser_recvNum = QtWidgets.QTextBrowser(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(22)
        sizePolicy.setHeightForWidth(
            self.textBrowser_recvNum.sizePolicy().hasHeightForWidth())
        self.textBrowser_recvNum.setSizePolicy(sizePolicy)
        self.textBrowser_recvNum.setObjectName("textBrowser_recvNum")
        self.horizontalLayout_2.addWidget(self.textBrowser_recvNum)
        self.pushButton_recvClear = QtWidgets.QPushButton(self.raw_data)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_recvClear.sizePolicy().hasHeightForWidth())
        self.pushButton_recvClear.setSizePolicy(sizePolicy)
        self.pushButton_recvClear.setObjectName("pushButton_recvClear")
        self.horizontalLayout_2.addWidget(self.pushButton_recvClear)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_13.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.raw_data, "")
        self.wave = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.wave.sizePolicy().hasHeightForWidth())
        self.wave.setSizePolicy(sizePolicy)
        self.wave.setObjectName("wave")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wave)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.wave)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listView = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.gridLayout_6.addWidget(self.listView, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_reset = QtWidgets.QPushButton(self.wave)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_reset.sizePolicy().hasHeightForWidth())
        self.pushButton_reset.setSizePolicy(sizePolicy)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout_5.addWidget(self.pushButton_reset, 0, 0, 1, 1)
        self.checkBox = [0] * 4
        self.checkBox[0] = QtWidgets.QCheckBox(self.wave)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox[0].sizePolicy().hasHeightForWidth())
        self.checkBox[0].setSizePolicy(sizePolicy)
        self.checkBox[0].setChecked(True)
        self.checkBox[0].setObjectName("checkBox_CH1")
        self.gridLayout_5.addWidget(self.checkBox[0], 0, 1, 1, 1)
        self.checkBox[1] = QtWidgets.QCheckBox(self.wave)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox[1].sizePolicy().hasHeightForWidth())
        self.checkBox[1].setSizePolicy(sizePolicy)
        self.checkBox[1].setChecked(True)
        self.checkBox[1].setObjectName("checkBox_CH2")
        self.gridLayout_5.addWidget(self.checkBox[1], 0, 2, 1, 1)
        self.checkBox[2] = QtWidgets.QCheckBox(self.wave)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox[2].sizePolicy().hasHeightForWidth())
        self.checkBox[2].setSizePolicy(sizePolicy)
        self.checkBox[2].setChecked(True)
        self.checkBox[2].setObjectName("checkBox_CH3")
        self.gridLayout_5.addWidget(self.checkBox[2], 0, 3, 1, 1)
        self.checkBox[3] = QtWidgets.QCheckBox(self.wave)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox[3].sizePolicy().hasHeightForWidth())
        self.checkBox[3].setSizePolicy(sizePolicy)
        self.checkBox[3].setChecked(True)
        self.checkBox[3].setObjectName("checkBox_CH4")
        self.gridLayout_5.addWidget(self.checkBox[3], 0, 4, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.wave, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1167, 22))
        self.menuBar.setObjectName("menuBar")
        MainWin.setMenuBar(self.menuBar)
        self.actionDeviceSetting = QtGui.QAction(MainWin)
        self.actionDeviceSetting.setObjectName("actionDeviceSetting")
        self.actionExit = QtGui.QAction(MainWin)
        self.actionExit.setObjectName("actionExit")
        self.actionSin = QtGui.QAction(MainWin)
        self.actionSin.setObjectName("actionSin")
        self.actionSquare = QtGui.QAction(MainWin)
        self.actionSquare.setObjectName("actionSquare")
        self.actionAbout_UI = QtGui.QAction(MainWin)
        self.actionAbout_UI.setObjectName("actionAbout_UI")
        self.actionRaw_Data = QtGui.QAction(MainWin)
        self.actionRaw_Data.setObjectName("actionRaw_Data")

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "MainWin"))
        self.groupBox_5.setTitle(_translate("MainWin", "串口设置："))
        self.label_23.setText(_translate("MainWin", "串口检测："))
        self.label_24.setText(_translate("MainWin", "串口选择："))
        self.label_25.setText(_translate("MainWin", "波特率："))
        self.label_26.setText(_translate("MainWin", "数据位："))
        self.label_27.setText(_translate("MainWin", "停止位："))
        self.label_28.setText(_translate("MainWin", "校验位："))
        self.pushButton_serialCheck.setText(_translate("MainWin", "检测串口"))
        self.comboBox_baudrate.setItemText(0, _translate("MainWin", "9600"))
        self.comboBox_baudrate.setItemText(1, _translate("MainWin", "1200"))
        self.comboBox_baudrate.setItemText(2, _translate("MainWin", "2400"))
        self.comboBox_baudrate.setItemText(3, _translate("MainWin", "4800"))
        self.comboBox_baudrate.setItemText(4, _translate("MainWin", "115200"))
        self.comboBox_baudrate.setItemText(5, _translate("MainWin", "2000000"))
        self.comboBox_dataBit.setItemText(0, _translate("MainWin", "8"))
        self.comboBox_stopBit.setItemText(0, _translate("MainWin", "1"))
        self.comboBox_parity.setItemText(0, _translate("MainWin", "N"))
        self.pushButton_serialOpen.setText(_translate("MainWin", "打开串口"))
        self.pushButton_serialClose.setText(_translate("MainWin", "关闭串口"))
        self.groupBox_6.setTitle(_translate("MainWin", "I2C设置："))
        self.label_33.setText(_translate("MainWin", "时钟频率："))
        self.label_34.setText(_translate("MainWin", "地址模式："))
        self.label_35.setText(_translate("MainWin", "地址："))
        self.label_32.setText(_translate("MainWin", "模式选择："))
        self.comboBox_i2c_addrMode.setItemText(0,
                                               _translate("MainWin", "7Bit"))
        self.comboBox_i2c_addrMode.setItemText(1,
                                               _translate("MainWin", "8Bit"))
        self.comboBox_i2c_speed.setItemText(0, _translate("MainWin", "100K"))
        self.comboBox_i2c_speed.setItemText(1, _translate("MainWin", "200K"))
        self.comboBox_i2c_speed.setItemText(2, _translate("MainWin", "400K"))
        self.comboBox_i2c_speed.setItemText(3, _translate("MainWin", "10K"))
        self.comboBox_i2c_speed.setItemText(4, _translate("MainWin", "20K"))
        self.comboBox_i2c_speed.setItemText(5, _translate("MainWin", "50K"))
        self.comboBox_i2c_mode.setItemText(0, _translate("MainWin", "主机模式"))
        self.comboBox_i2c_mode.setItemText(1, _translate("MainWin", "从机模式"))
        self.pushButton_i2cOpen.setText(_translate("MainWin", "打开I2C"))
        self.pushButton_i2cClose.setText(_translate("MainWin", "关闭I2C"))
        self.groupBox_7.setTitle(_translate("MainWin", "SPI设置："))
        self.label_37.setText(_translate("MainWin", "时钟频率："))
        self.label_36.setText(_translate("MainWin", "主从选择："))
        self.label_38.setText(_translate("MainWin", "帧格式："))
        self.label_39.setText(_translate("MainWin", "工作模式："))
        self.comboBox_spi_mode.setItemText(0, _translate("MainWin", "主机模式"))
        self.comboBox_spi_mode.setItemText(1, _translate("MainWin", "从机模式"))
        self.comboBox_spi_format.setItemText(0, _translate("MainWin", "MSB"))
        self.comboBox_spi_format.setItemText(1, _translate("MainWin", "LSB"))
        self.comboBox_spi_speed.setItemText(0, _translate("MainWin", "281K"))
        self.comboBox_spi_speed.setItemText(1, _translate("MainWin", "562K"))
        self.comboBox_spi_speed.setItemText(2, _translate("MainWin", "1.125M"))
        self.comboBox_spi_speed.setItemText(3, _translate("MainWin", "2.25M"))
        self.comboBox_spi_speed.setItemText(4, _translate("MainWin", "4.5M"))
        self.comboBox_spi_speed.setItemText(5, _translate("MainWin", "9M"))
        self.comboBox_spi_speed.setItemText(6, _translate("MainWin", "18M"))
        self.comboBox_spi_workmode.setItemText(
            0, _translate("MainWin", "模式0（00）"))
        self.comboBox_spi_workmode.setItemText(
            1, _translate("MainWin", "模式1（01）"))
        self.comboBox_spi_workmode.setItemText(
            2, _translate("MainWin", "模式2（10）"))
        self.comboBox_spi_workmode.setItemText(
            3, _translate("MainWin", "模式3（11）"))
        self.pushButton_i2cOpen_2.setText(_translate("MainWin", "打开SPI"))
        self.pushButton_i2cClose_2.setText(_translate("MainWin", "关闭SPI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.device_select),
                                  _translate("MainWin", "设置"))
        self.groupBox_4.setTitle(_translate("MainWin", "接收区"))
        self.groupBox_3.setTitle(_translate("MainWin", "发送区"))
        self.checkBox_HEXSend.setText(_translate("MainWin", "HEX 发送"))
        self.checkBox_sendByTime.setText(_translate("MainWin", "定时发送"))
        self.label_29.setText(_translate("MainWin", "ms/次"))
        self.pushButton_sendData.setText(_translate("MainWin", "发送数据"))
        self.pushButton_sendClear.setText(_translate("MainWin", "发送清除"))
        self.checkBox_HEXRecv.setText(_translate("MainWin", "HEX 接收"))
        self.label_31.setText(_translate("MainWin", "已发送："))
        self.label_30.setText(_translate("MainWin", "已接收："))
        self.pushButton_recvClear.setText(_translate("MainWin", "接收清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.raw_data),
                                  _translate("MainWin", "数据"))
        self.groupBox_2.setTitle(_translate("MainWin", "显示器"))
        self.pushButton_reset.setText(_translate("MainWin", "Reset"))
        self.checkBox[0].setText(_translate("MainWin", "CH1"))
        self.checkBox[1].setText(_translate("MainWin", "CH2"))
        self.checkBox[2].setText(_translate("MainWin", "CH3"))
        self.checkBox[3].setText(_translate("MainWin", "CH4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wave),
                                  _translate("MainWin", "波形"))
        self.actionDeviceSetting.setText(
            _translate("MainWin", "Device Setting"))
        self.actionExit.setText(_translate("MainWin", "Exit"))
        self.actionSin.setText(_translate("MainWin", "Sin"))
        self.actionSquare.setText(_translate("MainWin", "Square"))
        self.actionAbout_UI.setText(_translate("MainWin", "About UI"))
        self.actionRaw_Data.setText(_translate("MainWin", "Raw Data"))
